export const data = [
  {
    productName: "Clapping Monkey",
    category: "Toys",
    unitPrice: "$10.99",
    competitorPrice: "$12.99",
    currentStock: "50",
    forecast: "Need more stocks",
},
  {
    productName: "Hammer",
    category: "Tools",
    unitPrice: "$15.99",
    competitorPrice: "$17.99",
    currentStock: "36",
    forecast: "too much stocks",
  },
  {
    productName: "Hammer",
    category: "Tools",
    unitPrice: "$15.99",
    competitorPrice: "$17.99",
    currentStock: "36",
    forecast: "too much stocks",
  },
  {
    productName: "Hammer",
    category: "Tools",
    unitPrice: "$15.99",
    competitorPrice: "$17.99",
    currentStock: "36",
    forecast: "too much stocks",
  },
  {
    productName: "Hammer",
    category: "Tools",
    unitPrice: "$15.99",
    competitorPrice: "$17.99",
    currentStock: "36",
    forecast: "too much stocks",
  },
  {
    productName: "Hammer",
    category: "Tools",
    unitPrice: "$15.99",
    competitorPrice: "$17.99",
    currentStock: "36",
    forecast: "too much stocks",
  },
  {
    productName: "Hammer",
    category: "Tools",
    unitPrice: "$15.99",
    competitorPrice: "$17.99",
    currentStock: "36",
    forecast: "too much stocks",
  },
  {
    productName: "Hammer",
    category: "Tools",
    unitPrice: "$15.99",
    competitorPrice: "$17.99",
    currentStock: "36",
    forecast: "too much stocks",
  },
  {
    productName: "Hammer",
    category: "Tools",
    unitPrice: "$15.99",
    competitorPrice: "$17.99",
    currentStock: "36",
    forecast: "too much stocks",
  },
  {
    productName: "Hammer",
    category: "Tools",
    unitPrice: "$15.99",
    competitorPrice: "$17.99",
    currentStock: "36",
    forecast: "too much stocks",
  },
  {
    productName: "Hammer",
    category: "Tools",
    unitPrice: "$15.99",
    competitorPrice: "$17.99",
    currentStock: "36",
    forecast: "too much stocks",
  },
  {
    productName: "Hammer",
    category: "Tools",
    unitPrice: "$15.99",
    competitorPrice: "$17.99",
    currentStock: "36",
    forecast: "too much stocks",
  },
  {
    productName: "Hammer",
    category: "Tools",
    unitPrice: "$15.99",
    competitorPrice: "$17.99",
    currentStock: "36",
    forecast: "too much stocks",
  },
  {
    productName: "Hammer",
    category: "Tools",
    unitPrice: "$15.99",
    competitorPrice: "$17.99",
    currentStock: "36",
    forecast: "too much stocks",
  },
  {
    productName: "Hammer",
    category: "Tools",
    unitPrice: "$15.99",
    competitorPrice: "$17.99",
    currentStock: "36",
    forecast: "too much stocks",
  },
  {
    productName: "Hammer",
    category: "Tools",
    unitPrice: "$15.99",
    competitorPrice: "$17.99",
    currentStock: "36",
    forecast: "too much stocks",
  },
  {
    productName: "Hammer",
    category: "Tools",
    unitPrice: "$15.99",
    competitorPrice: "$17.99",
    currentStock: "36",
    forecast: "too much stocks",
  },
  {
    productName: "Hammer",
    category: "Tools",
    unitPrice: "$15.99",
    competitorPrice: "$17.99",
    currentStock: "36",
    forecast: "too much stocks",
  },
  {
    productName: "Hammer",
    category: "Tools",
    unitPrice: "$15.99",
    competitorPrice: "$17.99",
    currentStock: "36",
    forecast: "too much stocks",
  },
  {
    productName: "Hammer",
    category: "Tools",
    unitPrice: "$15.99",
    competitorPrice: "$17.99",
    currentStock: "36",
    forecast: "too much stocks",
  },
  {
    productName: "Hammer",
    category: "Tools",
    unitPrice: "$15.99",
    competitorPrice: "$17.99",
    currentStock: "36",
    forecast: "too much stocks",
  },
  {
    productName: "Hammer",
    category: "Tools",
    unitPrice: "$15.99",
    competitorPrice: "$17.99",
    currentStock: "36",
    forecast: "too much stocks",
  },
];
